Name = "fairground"
Level = "info"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API]
  [API.GRPC]
    Hosts = [
      "n01.testnet.vega.xyz:3002",
      "n02.testnet.vega.xyz:3002",
      "n03.testnet.vega.xyz:3002",
      "n04.testnet.vega.xyz:3002",
      "n05.testnet.vega.xyz:3002",
      "n06.testnet.vega.xyz:3007",
      "n07.testnet.vega.xyz:3007",
      "n08.testnet.vega.xyz:3007",
      "n09.testnet.vega.xyz:3007",
      "n10.testnet.vega.xyz:3007",
      "n11.testnet.vega.xyz:3007",
      "n12.testnet.vega.xyz:3007",
      "n13.testnet.vega.xyz:3007"
    ]
    Retries = 5
  [API.REST]
    Hosts = ["https://lb.testnet.vega.xyz/datanode/rest"]
  [API.GraphQL]
    Hosts = ["https://lb.testnet.vega.xyz/datanode/gql/query"]

[Console]
  URL = "console.fairground.wtf"
  LocalPort = 1847

[TokenDApp]
  URL = "token.fairground.wtf"
  LocalPort = 1848
