Name = "fairground"
Level = "info"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API]
  [API.GRPC]
    Hosts = ["api.n07.testnet.vega.xyz:3007", "api.n06.testnet.vega.xyz:3007", "api.n08.testnet.vega.xyz:3007", "api.n09.testnet.vega.xyz:3007", "api.n10.testnet.vega.xyz:3007", "api.n11.testnet.vega.xyz:3007", "api.n12.testnet.vega.xyz:3007"]
    Retries = 5
  [API.REST]
    Hosts = ["https://api.n06.testnet.vega.xyz", "https://api.n07.testnet.vega.xyz", "https://api.n08.testnet.vega.xyz", "https://api.n09.testnet.vega.xyz", "https://api.n10.testnet.vega.xyz", "https://api.n11.testnet.vega.xyz", "https://api.n12.testnet.vega.xyz"]
  [API.GraphQL]
    Hosts = ["https://api.n06.testnet.vega.xyz/graphql", "https://api.n07.testnet.vega.xyz/graphql", "https://api.n08.testnet.vega.xyz/graphql", "https://api.n09.testnet.vega.xyz/graphql", "https://api.n10.testnet.vega.xyz/graphql", "https://api.n11.testnet.vega.xyz/graphql", "https://api.n12.testnet.vega.xyz/graphql"]

[TokenDApp]
  URL = "token.fairground.wtf"
  LocalPort = 1848

[Console]
  URL = "console.fairground.wtf"
  LocalPort = 1847
