FileVersion = 2

Name = "testnet2"

[[Metadata]]
Key = "network"
Value = "testnet2"

[API]
  [API.GRPC]
    Hosts = [
      "tls://grpc.venom.tm.p2p.org:443",
      "vega-testnet.anyvalid.com:3007",
      "tls://testnet.grpc.vega.xprv.io:443",
      "vega-testnet.nodes.guru:3007",
      "testnet.vega.greenfield.xyz:3007",
      "tls://vega-testnet-data-grpc.commodum.io:443",
      "tls://vega-grpc.testnet.lovali.xyz:433",
      "vega-test-data.bharvest.io:3007"
    ]
    Retries = 5
  [API.GraphQL]
    Hosts = [
      "https://gql.venom.tm.p2p.org/graphql",
      "https://vega-testnet.anyvalid.com/graphql",
      "https://testnet.vega.xprv.io/datanode/query",
      "https://vega-testnet.nodes.guru:3008/graphql",
      "https://testnet.vega.greenfield.xyz:443/query",
      "https://vega-testnet-data-graphql.commodum.io/query",
      "https://vega-query.testnet.lovali.xyz:433/query",
      "https://vega-test-data.bharvest.io/graphql"
    ]
  [API.REST]
    Hosts = [
      "https://rest.venom.tm.p2p.org",
      "https://vega-testnet.anyvalid.com",
      "https://testnet.vega.xprv.io/datanode",
      "https://vega-testnet.nodes.guru:3009",
      "https://testnet.vega.greenfield.xyz:3009",
      "https://vega-testnet-data-rest.commodum.io",
      "https://vega-rest.testnet.lovali.xyz",
      "https://vega-test-data.bharvest.io:3009"
    ]

[Apps]
  Console = "https://validator-testnet.console.vega.xyz/"
  Governance = "https://validator-testnet.governance.vega.xyz/"
  Explorer = "https://validator-testnet.explorer.vega.xyz/"
